import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generatePDFReport = (lastCheckedData, stats) => {
  if (!lastCheckedData || Object.keys(lastCheckedData).length === 0) {
    alert("Prothome keyword check korun, tarpor PDF download korun.");
    return;
  }

  const doc = new jsPDF();
  const dateStr = new Date().toLocaleDateString();
  const score = Math.round((stats.totalUsed / (stats.totalUsed + stats.totalMissing)) * 100) || 0;

  // Filename logic
  let seedFileName = "SEO_Analysis_Report";
  try {
    const seedKey = Object.keys(lastCheckedData).find(k => k.toLowerCase().includes('seed'));
    if (seedKey && lastCheckedData[seedKey].length > 0) {
      seedFileName = lastCheckedData[seedKey][0].text
        .trim()
        .replace(/[^a-z0-9\s]/gi, '')
        .replace(/\s+/g, '_');
    }
  } catch (e) {
    console.error("Filename error:", e);
  }

  try {
    // --- TOP ACCENT BAR ---
    doc.setFillColor(79, 70, 229); // Indigo-600
    doc.rect(0, 0, 210, 40, 'F');

    // --- LOGO / TITLE ---
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("SEO CONTENT AUDIT", 14, 20);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by Shipon Talukdar • ${dateStr}`, 14, 28);

    // --- SCORE CARD ---
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(150, 10, 45, 20, 3, 3, 'FD');
    doc.setTextColor(79, 70, 229);
    doc.setFontSize(8);
    doc.text("SCORE", 172.5, 18, { align: 'center' });
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`${score}%`, 172.5, 26, { align: 'center' });

    // --- EXECUTIVE SUMMARY SECTION ---
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(16);
    doc.text("Executive Summary", 14, 55);

    // Draw custom stat boxes
    const drawStatBox = (x, y, label, value, color) => {
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(x, y, 60, 25, 2, 2, 'F');
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        doc.text(label.toUpperCase(), x + 30, y + 10, { align: 'center' });
        doc.setFontSize(14);
        doc.setTextColor(color[0], color[1], color[2]);
        doc.text(value.toString(), x + 30, y + 20, { align: 'center' });
    };

    drawStatBox(14, 62, "Found Keywords", stats.totalUsed, [16, 185, 129]);
    drawStatBox(80, 62, "Missing Keywords", stats.totalMissing, [244, 63, 94]);
    drawStatBox(146, 62, "Total Checked", stats.totalUsed + stats.totalMissing, [79, 70, 229]);

    let finalY = 100;

    // --- DETAIL SECTIONS ---
    Object.keys(lastCheckedData).forEach((category) => {
      const items = lastCheckedData[category];
      const usedCount = items.filter(i => i.isFound).length;
      const missingCount = items.length - usedCount;

      if (finalY > 230) {
        doc.addPage();
        finalY = 20;
      }

      // Section Header with background
      doc.setFillColor(241, 245, 249);
      doc.rect(14, finalY, 182, 10, 'F');
      doc.setTextColor(51, 65, 85);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.text(`${category.toUpperCase()}`, 18, finalY + 6.5);
      
      // Stats in header
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(`FOUND: ${usedCount} | MISSING: ${missingCount}`, 190, finalY + 6.5, { align: 'right' });

      const tableBody = items.map(item => [
        item.text,
        item.isFound ? "OPTIMIZED" : "MISSING"
      ]);

      autoTable(doc, {
        startY: finalY + 10,
        head: [['Keyword Phrase', 'Status']],
        body: tableBody,
        theme: 'striped',
        styles: { fontSize: 8, cellPadding: 3, font: "helvetica" },
        headStyles: { fillColor: [71, 85, 105], textColor: [255, 255, 255], fontStyle: 'bold' },
        columnStyles: {
            1: { cellWidth: 40, halign: 'center' }
        },
        didParseCell: function (data) {
          if (data.column.index === 1) {
            if (data.cell.raw === "OPTIMIZED") {
              data.cell.styles.textColor = [22, 163, 74];
              data.cell.styles.fontStyle = 'bold';
            } else {
              data.cell.styles.textColor = [220, 38, 38];
              data.cell.styles.fontStyle = 'bold';
            }
          }
        }
      });

      finalY = doc.lastAutoTable.finalY + 15;
    });

    // --- FOOTER ---
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setDrawColor(226, 232, 240);
      doc.line(14, 280, 196, 280);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Shipon Talukdar • SEO Report`, 14, 287);
      doc.text(`Page ${i} of ${pageCount}`, 196, 287, { align: 'right' });
    }

    doc.save(`${seedFileName}_Report.pdf`);
  } catch (error) {
    console.error("PDF Generation Error:", error);
    alert("PDF report generate Error.");
  }
};
